# Generated by Django 4.1.3 on 2022-12-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
